# Generated by Django 5.0.1 on 2024-01-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_course_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'образовательный модуль', 'verbose_name_plural': 'образовательные модули'},
        ),
    ]
